### ISSUE TITLE
Saving issue MYSQL

### ISSUE THREAD

**Issue by fbagjug** [netherfoam/MaxBans-4.0#57]
Hello, I seem to be having an issue with the bans saving to the database. All of the warns and mutes log and store in the database but the bans do not. If you know this issue I would appreciate the help. Thanks

**Comment by fbagjug** [comment]
Ok I figured it logs normal bans for example /ban but I cant get the /ban working with a time

**Comment by fbagjug** [comment]
Ok update. Found another issue. I banned myself on factions and was able to rejoin the hub. I didn't want that to happen :/

**Comment by netherfoam** [comment]
Are you using `MaxBans`, or `MaxBans Plus`?

**Comment by fbagjug** [comment]
MaxBans Plus

**Comment by fbagjug** [comment]
Basically the server isn't reading the DB on join

**Comment by fbagjug** [comment]
Found another issue. Banned myself on the factions server and it come up in chat but didnt kick me/ban me from the server. When I left and tryed to rejoin factions it said i was banned and wouldnt join.

**Comment by netherfoam** [comment]
Okay I'm going to need a lot more information to diagnose your issue. Please add:
* The full output of your server log on boot
* The output of your server log when banning a player 
* The output of your server log when a banned player joins
* The message you receive when banning a player in game (screenshot)
* The config.yml for MaxBans plus of both servers

Also, try disable all your plugins except MaxBans Plus and let me know if you are able to replicate the issue still

**Comment by netherfoam** [comment]
Did you find the error message in the logs?

**Comment by netherfoam** [comment]
Can't resolve this without a diagnosis. Closing it until further notice
